### PR TITLE
Croatian Language Translation

### PR DESCRIPTION
**Pull request by dcvikl**
The Translation is 100% complete.

### CODE REVIEW

**Comment by dcvikl** [comment]
Made a full translation to Croatian language (hr_HR).

**Comment by connerbw** [comment]
Thanks!

We use Transifex. When we release a new version, a bunch of scripts pull everything from Transifex and replaces everything automatically. Instead of approving this PR, which would get deleted when we update from Transifex, can I ask you upload your files there?

https://www.transifex.com/pressbooks/pressbooks-book/language/hr_HR/

CC: @SteelWagstaff

**Comment by dcvikl** [comment]
Yes of course. I have put up a language request but didn't get a response that it was accepted.

**Comment by dcvikl** [comment]
Hi,

 
Sorry but I have just found the confirmation for the Croatian language on Transiflex will upload the translations during the weekend.

**Comment by connerbw** [comment]
I double checked that you are a translator:

image

I'm closing this PR and looking forward to the Transifex upload. 

Regards,

**Pull request closed without merging**
