### PR TITLE
Travis replacement in favor of Github Actions

### PR DESCRIPTION
**Pull request by arzola**
Solves #743 

Travis replacement

This Github Action release a draft release using tags if linting, tests and coverage pass

### CODE REVIEW

**Review by ho-man-chan — CHANGES_REQUESTED** [review]
LGTM. aside from the tag version needing a small change from 'v*.*.*' to '*.*.*' in line 6 and the missing notification (email and Slack) feature in the github action comparing to TravisCI.

**Comment by arzola** [comment]
@ho-man-chan I fixed the tags matching string and also I added an action to send an slack message, email notifications are already included on github actions

**Review by ho-man-chan — CHANGES_REQUESTED** [review]
LGTM. Nice pipeline!!
A note for slack:
After reviewing the slack messages sent by this slack action, it seems a little messy. It looks like our slack already has a GitHub integration as well, so this would be redundant. Good to know it works and it has potential for another task in the future! For now, I think it would be best to remove it. What do you think?

**Comment by arzola** [comment]
@ho-man-chan I removed the slack action integration doesn't make sense to have it thanks for reviewing

**Review by ho-man-chan — APPROVED** [review]
LGTM

**Pull request merged**
