### PR TITLE
Spanish for Costa Rica

### PR DESCRIPTION
**Pull request by marbaque**
Added Spanish for Costa Rica language files

### CODE REVIEW

**Comment by greatislander** [comment]
To add this translations to the Transifex platform, @SteelWagstaff or @ho-man-chan will need to:

1. Merge this PR.
2. Add `es_CR` to the [project's languages](https://www.transifex.com/pressbooks/pressbooks-book/languages/) in Transifex.
3. Pull the dev branch with the Costa Rican Spanish translations locally, then run the following Transifex CLI commands to push the new language to Transifex:
    ```bash
     tx push -s -l es_CR
     ```

**Review by SteelWagstaff — APPROVED** [review]
Looks good to me. Gracias por la contribución, @marbaque!

**Comment by SteelWagstaff** [comment]
@greatislander 
I did steps 1-3 and saw this in console
Screenshot from 2021-04-23 10-05-01
Is there anything else I can/should do to confirm in Transifex that the process did what it was supposed to do?

**Comment by greatislander** [comment]
Sorry @SteelWagstaff — it should have been:

```
tx push -t -l es_CR
```

**Comment by SteelWagstaff** [comment]
Done. That makes sense. I'll add this to our internal documentation for future reference. Thanks!

**Pull request merged**
