### PR TITLE
Pluralization fix

### PR DESCRIPTION
**Pull request by arzola**
This PR is part of https://github.com/pressbooks/pressbooks/pull/2348

### CODE REVIEW

**Review by SteelWagstaff — CHANGES_REQUESTED** [review]
Two problems I see:
1. `Warning: count(): Parameter must be an array or an object that implements Countable in /srv/www/pressbooks.test/current/web/app/themes/pressbooks-book/partials/content-single.php on line 69`
2. When I have just a single author assigned, the heading text should read: 'About the author', not 'About the Authors'
Screenshot from 2021-09-01 09-21-57

**Comment by arzola** [comment]
@SteelWagstaff you were right I didn't push my latest changes I fixed this

**Review by SteelWagstaff — CHANGES_REQUESTED** [review]
Works as expected, though I notice that we aren't providing localization for the string 'About the Author/s' string. We should. Can you please add?

**Review by SteelWagstaff — APPROVED** [review]
LGTM

**Pull request merged**
