### PR TITLE
Fix positioning for images without caption in PDFs

### LINKED ISSUE #791: centered images with no captions are not getting centered in PDF exports
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

If I insert an image in a chapter, with no captions,  and center it ... PDF exports are not centering.

Expected behaviour: 
Centered images without captions are centered in PDF exports. 

See: 
https://pressbookstest.pressbooks.com/wp/wp-admin/post.php?post=179&action=edit

Note, there is/was a function that wrapped non-captioned images in a div, so that eg: 

```
<img class="size-full wp-image-48 aligncenter" src="https://pressbooks.com/app/uploads/sites/29132/2014/03/hugh-lookout_reasonably_small.jpeg" alt="akhfkj" width="128" height="128" />
```

Should get converted to the following in the XHTML export, which then feeds PDF (and EPUB -- I did not test in epub):

```
<div class="wp-nocaption centered">
<img class="size-full wp-image-48 aligncenter" src="https://pressbooks.com/app/uploads/sites/29132/2014/03/hugh-lookout_reasonably_small.jpeg" alt="akhfkj" width="128" height="128" />
</div>
```

But this doesn't seem to be happening, xhtml exports show no `<div class="wp-nocaption">` wrapper on images without captions.

We've seen this before, see for a more thorough description: 
https://github.com/pressbooks/pressbooks/issues/263

### Steps to Reproduce

1. insert an image in a chapter
2. Center it using the visual editor
3. export PDF
4. Look at the image
5. it ain't centered

**Expected behavior:** 
The image is centered.

**Actual behavior:** 
It wasn't centered.

### PR DESCRIPTION
**Pull request by fdalcin**
This should fix #791 and #792 

This PR attempts to solve PDF and EPUB floating image positioning.
It also fixes a GitHub pipeline issue that @ho-man-chan mentioned.

#### How to test
* Create a book with floating (left, right) and centered images with no caption
* Check that the book renders properly as web pages
* Export a PDF and/or EPUB version of the book and check if the content is properly rendered
* Make sure that inline images keep rendering as inline

### CODE REVIEW

**Review by SteelWagstaff — CHANGES_REQUESTED** [review]
@fdalcin Images with aligncenter are missing display:block for web and epub exports. As a result, images are not center aligned unless there's a clear paragraph break between them and the following text. See examples in
Screenshot from 2021-06-22 14-25-00
Screenshot from 2021-06-22 14-24-48
Second, we can avoid repitition by simply adding a rule for the elements themselves which does not specify the $type, and then adding any distinctive needs for epub, prince, and/or web separately.

**Comment by SteelWagstaff** [comment]
For example, we could write the changes as something like:
```
p {
  img {
    &.aligncenter {
      margin: if-map-get($image-wrapper-margin-top, $type) auto if-map-get($image-wrapper-margin-bottom, $type);
      text-align: center;
      display: block;

      @include caption-text-align(center);
    }

    &.alignleft {
      float: left;
      margin: if-map-get($image-wrapper-margin-top, $type) if-map-get($image-alignleft-margin-right, $type) if-map-get($floated-image-wrapper-margin-bottom, $type) 0;
      padding-right: 0;

      @include caption-text-align(left);
    }

    &.alignright {
      float: right;
      margin: if-map-get($image-wrapper-margin-top, $type) 0 if-map-get($floated-image-wrapper-margin-bottom, $type) if-map-get($image-alignright-margin-left, $type);
      padding-left: 0;

      @include caption-text-align(right);
    }

    @if $type != 'web' {
      &.aligncenter, &.alignleft, &.alignright {
        max-width: 50%;
      }
    }
  }
}
```

**Comment by fdalcin** [comment]
Thanks for your review @SteelWagstaff, I'll work on improving that

**Comment by SteelWagstaff** [comment]
I have a commit ready. You mind if I send to branch?

**Comment by fdalcin** [comment]
Sure, go ahead, thanks.

**Review by SteelWagstaff — APPROVED** [review]
Looks good to me locally.

**Pull request merged**
